"""创建了User和post表

Revision ID: 773a80dc5a61
Revises: 2e4576a63c75
Create Date: 2020-05-19 15:06:18.251407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773a80dc5a61'
down_revision = '2e4576a63c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
